repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.27.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: ^src/backend/(?:.*/)*.*$
        args: [--target-version=py39]

  # Lint / autoformat: Python code
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.248"
    hooks:
      - id: ruff
        files: ^src/backend/(?:.*/)*.*$
        args: [--fix, --exit-non-zero-on-fix]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        args: [--ignore-unknown, --no-error-on-unmatched-pattern, "!chart/**"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
        args: [--fix]
